services:
  - name: gem-badge
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python gem_downloads_badge.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
